# Generated by Django 5.2 on 2026-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
